"""add student lecturer face_data course session attendance tables

Revision ID: 13e27d19155e
Revises: 0002_add_profile_fields
Create Date: 2026-01-09 16:13:10.895189

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e27d19155e'
down_revision = '0002_add_profile_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop dependent tables, then drop the old user table
    op.drop_table('attendance')
    op.drop_table('session')
    op.drop_table('course')
    op.drop_table('face_data')
    op.drop_table('lecturer')
    op.drop_table('student')
    op.drop_table('user')
    
    # Now recreate them with UUID foreign keys to users table
    op.create_table('student',
        sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('matric_no', sa.String(length=50), nullable=False),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('student_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id'),
        sa.UniqueConstraint('matric_no')
    )
    
    op.create_table('lecturer',
        sa.Column('lecturer_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('lecturer_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id')
    )
    
    op.create_table('face_data',
        sa.Column('face_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('face_template', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('face_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    
    op.create_table('course',
        sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('course_name', sa.String(length=255), nullable=False),
        sa.Column('course_code', sa.String(length=20), nullable=False),
        sa.Column('lecturer_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('course_id'),
        sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.lecturer_id'], ondelete='SET NULL'),
        sa.UniqueConstraint('course_code')
    )
    
    op.create_table('session',
        sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('qr_code', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('session_id'),
        sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE')
    )
    
    op.create_table('attendance',
        sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
        sa.PrimaryKeyConstraint('attendance_id'),
        sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE')
    )
    
    # Fix users table index
    op.drop_constraint('uq_users_firebase_uid', 'users', type_='unique')
    op.drop_index('ix_users_firebase_uid', table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index('ix_users_firebase_uid', 'users', ['firebase_uid'], unique=False)
    op.create_unique_constraint('uq_users_firebase_uid', 'users', ['firebase_uid'])
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_user_id_fkey', 'student', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_student', 'student', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'student', type_='unique')
    op.alter_column('student', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('session', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('session', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'lecturer', type_='foreignkey')
    op.create_foreign_key('lecturer_user_id_fkey', 'lecturer', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_lecturer', 'lecturer', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'lecturer', type_='unique')
    op.alter_column('lecturer', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'face_data', type_='foreignkey')
    op.create_foreign_key('face_data_user_id_fkey', 'face_data', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('face_data', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('attendance', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('attendance', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='USER_pkey'),
    sa.UniqueConstraint('email', name='USER_email_key')
    )
    # ### end Alembic commands ###
